config/routes.rb
Rails.application.routes.draw do

    root 'projects#index'

    resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	before_action :set_project, only: [:show, :edit, :update, :destroy]
	
	def index
		@projects = Project.all
	end
	
	def new
		@project = Project.new
	end
	
	def create
		@project = Project.new(project_params)
		
		if @project.save
			flash[:notice] = "Project has been created."
			redirect_to @project
		else
			flash.now[:alert] = "Project has not been created."
			render "new"
		end		
	end
	
	def show
	end

	def edit
	end

	def update
		if @project.update(project_params)
			flash[:notice] = "Project has been updated."
			redirect_to @project
		else
			flash.now[:alert] = "Project has not been updated."
			render "edit"
		end	
	end
	
	def destroy
		@project.destroy

		flash[:notice] = "Project has been deleted."
		redirect_to projects_path		
	end
	
	private
	
	def project_params
		params.require(:project).permit(:name, :description)
	end

	def set_project
		@project = Project.find(params[:id])
		rescue ActiveRecord::RecordNotFound
		flash[:alert] = "The project you are looking for could not be found."
		redirect_to projects_path
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Ticketee" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '**defaults**', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Ticketee", root_path, class: "navbar-brand" %>
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="collapse navbar-collapse" id="collapse">
			<ul class="nav navbar-nav">
				<li class="<%= "active" if current_page?("/") %>">
					<%= link_to "Home", root_path %>
				</li>
			</ul>
		</div>
</div>
</nav>

<div class="container">
	<% flash.each do |key, message| %>
	<div class="alert alert-<%= key %>">
		<%= message %>
	</div>	
	<% end %>
	
	<%= yield %>
</div>
	
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(project) do |f| %>	
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<header>
	<h1>Edit Project</h1>
</header>
	<%= render "form", project: @project %>

app/views/projects/index.html.erb
<header>
	<h1>Projects</h1>
	
	<ul class="actions">
	   <li><%= link_to "New Project", new_project_path, class: "new" %></li>
	</ul>   
</header>



<div id="projects">
	<% @projects.each do |project| %>
		<h2><%= link_to project.name, project %></h2>
		<p><%= project.description %></p>
	<% end %>
</div>

app/views/projects/new.html.erb
<header>
	<h1>New Project</h1>
</header>
	
<% if @project.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@project.errors.count, "error") %>
prohibited this project from being saved:</h2>
<ul>
<% @project.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<%= simple_form_for(@project) do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.button :submit,class: "btn-primary" %>
<% end %>

app/views/projects/show.html.erb
<header>
	<h1><%= @project.name %></h1>
	<% @title = "Sublime Text 3 - Projects - Ticketee" %>
	<ul class="actions">
		<li><%= link_to "Edit Project",
			edit_project_path(@project), class: "edit" %></li>
		<li><%= link_to "Delete Project",
			project_path(@project),
			method: :delete,
			data: { confirm: "Are you sure you want to delete this project?" },
			class: "btn btn-danger" %></li>
	</ul>
</header>